### PR TITLE
Modified matcher to use new sift package

### PR DESCRIPTION
**Pull request by Mattchewone**
Changed the `matcher` from the `feathers-commons` package to use the [sift](https://github.com/crcn/sift.js) package to allow for more refined query matching. 

This improves `$in` support to be more like `mongodb`.

### CODE REVIEW

**Comment by daffl** [comment]
Sweet, I've been meaning to look into this.

One problem I see with this change at the moment is that it will filter the entire list for every item to see if it matches instead of just using the sifted list right away.

I think changing https://github.com/feathersjs/feathers-memory/blob/master/src/index.js#L35 to

```js
 let values = sift(query, _.values(this.store));
```

And removing https://github.com/feathersjs/feathers-memory/blob/master/src/index.js#L22 (it's not documented anyway) will give us better performance.

**Comment by Mattchewone** [comment]
Hey @daffl thanks for the update. 

I didn't want to remove the option as I wasn't sure if this was something people would be using. But I have updated with your suggestion.

Thanks

**Comment by Mattchewone** [comment]
I have just realised I have removed the test for the custom $sort. 

Let me just fix that.

**Comment by daffl** [comment]
Actually that's a good call. Should we change it to still support that option? Would mean changing https://github.com/feathersjs/feathers-memory/pull/57/files#diff-1fdf421c05c1140f6d71444ea2b27638L22 to

```js
this._matcher = options.matcher;
```

And the `sift` part to

```js
let values = _.values(this.store);

if(this._matcher) {
  values.filter(this._matcher(query))
} else {
  values = sift(query, values);
}
```

Thoughts?

**Comment by Mattchewone** [comment]
It looks good to me, it would also mean better backward compatibility if there are some users using a custom matcher. 

I think keeping the option allows a bit more flexibility.

Shall we agree on keeping the option?

**Comment by daffl** [comment]
Yes, I think keeping it makes sense.

**Comment by marshallswain** [comment]
Released as `feathers-memory@1.3.0`  Thanks @Mattchewone!!!

**Pull request merged**
